# Generated by Django 3.0.8 on 2020-09-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20200907_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
