# Generated by Django 3.0.8 on 2020-09-07 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_shortener_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortener',
            old_name='tmiestamp',
            new_name='timestamp',
        ),
    ]
