# Generated by Django 3.0.8 on 2020-09-07 20:43

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20200908_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='url',
            field=models.URLField(validators=[shortener.validators.validate_url_endings]),
        ),
    ]
